config/routes.rb
Rails.application.routes.draw do
  resources :payments do
    collection do
      post :receive_webhook
    end
  end
  resources :campaign_complaints
  resources :doas
  resources :campaigns
  resources :products
  resources :suppliers
  resources :donations

  #User
  get 'users/profil/:name', to: 'users#index', as: 'users_index'
  get 'getting-started', to: 'users#getting_started', as: 'getting_started'

  #Devise
  devise_for :users, controllers: { omniauth_callbacks: 'users/omniauth_callbacks',
                                    registrations: 'users/registrations',
                                    confirmations: 'users/confirmations',
                                    sessions: 'users/sessions',
                                    passwords: 'users/passwords' }

  #Rails Admin
  mount RailsAdmin::Engine => '/admin', as: 'rails_admin'

  #CKEditor
  mount Ckeditor::Engine => '/ckeditor'

  #Root
  root to: "home#index"

  #Campaign
  post 'campaigns/approval/:id', to: 'campaigns#approval', as: 'approve_campaign'
  post 'campaigns/decline/:id', to: 'campaigns#decline', as: 'decline_campaign'
  post 'campaigns/save-donation/:id', to: 'campaigns#save_donation', as: 'save_donation'
  post 'campaigns/:id', to: 'campaigns#donate', as: 'campaign_donate'

  match "notification/handle" => "campaigns#receive_webhook", via: [:post]

  #Campaign Complaint
  get 'campaign_complaints/campaign/:id', to: "campaign_complaints#show_all", as: 'show_all_complaints'

  #Doa
  get '/doas/change-status/:id', to: "doas#change_status", as: 'change_status'

  #MONTHLY REPORT
  get 'monthly_product_report/:month', to: "report_products#monthly", as: 'month_product'
  get 'monthly_product_report_export/:month', to: "report_products#export", as: 'month_product_export'
  get 'monthly_donation_report/:month', to: "report_donation#monthly", as: 'month_donation'
  get 'monthly_donation_report_export/:month', to: "report_donation#export", as: 'month_donation_export'

  #NEWSLETTER
  get 'newsletters', to: 'newsletters#index'
  post 'newsletters/create', to: 'newsletters#create'

  #Cek Resi
  get 'cek_resi', to: 'home#cek_resi'

  #Donation
  get 'donation/cek', to: 'donations#cek', as: 'donation_cek'
  get 'campaigns/refund-donation/:order_id', to: 'campaigns#refund', as: 'refund_donation'

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/doa.rb
class Doa < ApplicationRecord
  belongs_to :user
  belongs_to :doa_status  

  validates :title, presence: {message: "tidak boleh kosong"}
  validates :doa, presence: {message: "tidak boleh kosong"}

  def self.update_status(current_status, id_doa, user_id)
    doa = Doa.find(id_doa)
    doa.update(current_status)

    return Doa.where("user_id = ?", user_id).order(created_at: :desc)
  end

  def self.filter(doa_filter)
    if doa_filter
      return where('doa_status_id = ?', doa_filter)
    else
      return all
    end
  end
end

app/controllers/doas_controller.rb
class DoasController < ApplicationController
  before_action :find_doa, only: [:show, :edit, :update, :destroy]
  before_action :check_doa_status, only: [:create]

  def index
    if current_user
      display_all_doas
      respond_to do |format|
        format.js
        format.html
      end
    else
      redirect_to new_user_session_path
    end
  end
  
  def change_status
    if @doas = Doa.update_status(
                    params.require(change_status_path).permit(:doa_status_id), 
                    params[:id], 
                    current_user.id
                  )
    
      @statuses = DoaStatus.all
      respond_to do |format|
        format.js { render :action => "index" }
        format.html
      end
    end
  end

  def destroy
    @doa.destroy
    display_all_doas
    respond_to do |format|
      format.js { render :action => "index" }
      format.html
    end
  end

  def show
    only_user_and_admin @doa
  end

  def new
    redirect_to new_user_session_path unless current_user
    @doa = Doa.new
  end

  def create
    @doa = Doa.new(doa_params)
      if @doa.save
        redirect_to( doas_path, 
                     notice: 'Doa berhasil tersimpan'
                    )
      else 
        @doa.valid?
        flash[:alert] = @doa.errors.full_messages[0]
        render :action => :new
      end
  end

  def edit
    only_user_and_admin @doa
  end

  def update
    @doa.update(doa_params)
    redirect_to doas_path
  end

  private
    def find_doa
      if Doa.exists?(params[:id])
       @doa = Doa.find(params[:id])
      else
        redirect_to root_path
      end
    end

    def doa_params
      params.require(:doa).permit(:title, :doa, :doa_desc, :expired_at, :user_id)
    end

    def display_all_doas
      @doas = Doa.filter(params[:doa_filter])
                 .where("user_id = ?", "#{current_user.id}")
                 .order(created_at: :desc)

      @statuses = DoaStatus.all
    end

    def check_doa_status
      DoaStatus.new(:id => 1,:status_name => "Berjalan").save unless DoaStatus.any?
    end
end

app/views/doas/_doas.html.slim
div class="btn-group mt-4" style="display:inline-block"
  div class="col-lg-2" style="display:inline-block"
    = link_to "All", doas_path, remote: true
  - @statuses.each do |status|
    -next unless @doas.exists?(:doa_status_id => status.id)
    div class="col-lg-2" style="display:inline-block"
      = link_to "#{status.status_name}", doas_path(:doa_filter => status.id), remote: true
  br/
  br/

  - @statuses.each do |status|
    -next unless @doas.exists?(:doa_status_id => status.id)
    h3= status.status_name
    table id="1" class="table"
    	tr
    		th width="200" Status
    		th width="200" Doa
    		th width="200" Dibuat Tanggal
    		th width="200" Target Waktu Pencapaian
    		th width="200" colspan="3" Action
      	- @doas.where("doa_status_id = ?", "#{status.id}").each do |doa|
      	  tr class="#{doa.id}"
      	    td id="status-doa"
              = form_for change_status_path(doa.id), :method => 'get'  do |f|
                = f.collection_select(:doa_status_id, @statuses, :id, :status_name, {:selected => doa.doa_status.id}, {:data => {:remote => true, :url => change_status_path(doa.id)}, :class => "form-control" }) 
            td = doa.title
      	    td = doa.created_at.to_date
      	    td = doa.expired_at
      	    td = link_to "Lihat", doa
            td = link_to "Ubah", edit_doa_path(doa.id)
            td = link_to 'Hapus', doa, data: { confirm: 'Apakah anda yakin?' }, method: :delete, remote: true

    br/

app/views/doas/edit.html.slim
.bg-purple-top
.container.mt-4.mb-4 style="position:relative"
  .content
    h2 Edit Wishlist
    = simple_form_for(@doa) do |f|
      .form-group
        = f.input :title, label: 'Nama Doa'
        = f.input :doa, as: :ckeditor, input_html: { class: 'ckeditor'}, label: 'Doa'
        = f.input :doa_desc, as: :ckeditor, input_html: { class: 'ckeditor'}, label: 'Deskripsi Doa'
        = f.input :user_id, :as => :hidden, :input_html => { :value => "#{current_user.id}" }
        = f.submit "Sunting Doa", class: "submit-btn"

app/views/doas/index.html.slim
div class="container mt-4 mb-4"
  = link_to "Mari berdoa", new_doa_path, :class => "btn btn-primary"
  br
  div id="table-doa"
    = render partial: "doas", locales: {doas: @doas}

app/views/doas/index.js.erb
$('#table-doa').html("<%= j(render partial: 'doas', locales: {doas: @doas}) %>)")

app/views/doas/new.html.slim
.bg-purple-top
.container.mt-4.mb-4 style="position:relative"
  .content
    h2 Tambahkan doa baru
    = simple_form_for(@doa) do |f|
        .form-group
            = f.input :title, label: 'Nama doa'
            = f.input :doa, as: :ckeditor, input_html: { class: 'ckeditor'}, label: 'Doa'
            = f.input :doa_desc, as: :ckeditor, input_html: { class: 'ckeditor'}, label: 'Deskripsi Doa'
            = f.input :expired_at, as: :date, label: 'Target Waktu Pencapaian'
            = f.input :user_id, :as => :hidden, :input_html => { :value => "#{current_user.id}" }
    
            = f.submit "Simpan Doa", class: 'submit-btn'

app/views/doas/show.html.slim
css:
  body{
    background-color: #f0f1f7;
  }
.container.mt-4.mb-4
  .content
    h2= @doa.title
    p= @doa.doa_status.status_name
    
    p= raw @doa.doa
    hr
    p= raw @doa.doa_desc
    hr
    p 
      | Dibuat : 
      = @doa.created_at
    p
      | Berakhir : 
      = @doa.expired_at

  .content
    = link_to "Perbaharui Doa", edit_doa_path(@doa)

  .content
    = link_to "back", :back