config/routes.rb
Rails.application.routes.draw do
  resources :payments do
    collection do
      post :receive_webhook
    end
  end
  resources :campaign_complaints
  resources :doas
  resources :campaigns
  resources :products
  resources :suppliers
  resources :donations

  #User
  get 'users/profil/:name', to: 'users#index', as: 'users_index'
  get 'getting-started', to: 'users#getting_started', as: 'getting_started'

  #Devise
  devise_for :users, controllers: { omniauth_callbacks: 'users/omniauth_callbacks',
                                    registrations: 'users/registrations',
                                    confirmations: 'users/confirmations',
                                    sessions: 'users/sessions',
                                    passwords: 'users/passwords' }

  #Rails Admin
  mount RailsAdmin::Engine => '/admin', as: 'rails_admin'

  #CKEditor
  mount Ckeditor::Engine => '/ckeditor'

  #Root
  root to: "home#index"

  #Campaign
  post 'campaigns/approval/:id', to: 'campaigns#approval', as: 'approve_campaign'
  post 'campaigns/decline/:id', to: 'campaigns#decline', as: 'decline_campaign'
  post 'campaigns/save-donation/:id', to: 'campaigns#save_donation', as: 'save_donation'
  post 'campaigns/:id', to: 'campaigns#donate', as: 'campaign_donate'

  match "notification/handle" => "campaigns#receive_webhook", via: [:post]

  #Campaign Complaint
  get 'campaign_complaints/campaign/:id', to: "campaign_complaints#show_all", as: 'show_all_complaints'

  #Doa
  get '/doas/change-status/:id', to: "doas#change_status", as: 'change_status'

  #MONTHLY REPORT
  get 'monthly_product_report/:month', to: "report_products#monthly", as: 'month_product'
  get 'monthly_product_report_export/:month', to: "report_products#export", as: 'month_product_export'
  get 'monthly_donation_report/:month', to: "report_donation#monthly", as: 'month_donation'
  get 'monthly_donation_report_export/:month', to: "report_donation#export", as: 'month_donation_export'

  #NEWSLETTER
  get 'newsletters', to: 'newsletters#index'
  post 'newsletters/create', to: 'newsletters#create'

  #Cek Resi
  get 'cek_resi', to: 'home#cek_resi'

  #Donation
  get 'donation/cek', to: 'donations#cek', as: 'donation_cek'
  get 'campaigns/refund-donation/:order_id', to: 'campaigns#refund', as: 'refund_donation'

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  include CampaignsHelper

	def index
    check_data
    sign_in(User.find(params[:id]), scope: :user) if params[:id]
		@campaigns = Campaign.where(:status => "approved")
                         .order(created_at: :desc)
                         .last(3)
		@total = Campaign.where(:status => "approved").count
	end

	def cek_resi
	end

  def check_data
    put_user_data
    flash[:info] = nil

    if current_user

      @datas.each do |data|
        @filled_data_count -= 1 if current_user.send(data).nil? ||  current_user.send(data) == ""
      end

      flash[:info] = "Lengkapi data diri anda (#{@filled_data_count} / #{@datas.count})" unless @filled_data_count == @datas.count
    end
  end
end

app/helpers/home_helper.rb
module HomeHelper
end

app/views/home/cek_resi.html.slim
.container.mt-4.mb-4
	.row.h-100.align-items-center
		.col-lg-10.mx-auto
			.card.h-100 align="center"
				.card-body align="center"
					h3.card-title.text-primary
						| Cek Resi
					h5.card-title.text-secondary
						| Masukan Order ID
					= form_tag donation_cek_path(:id), class: "form-inline col-lg-12 mx-auto", :method => 'get' do
						= text_field_tag :id, nil, placeholder:'Donation-XX-XX_XXXXXXXXX', class: "form-control mt-5 col-lg-12"

						= button_tag(type: "submit", class: "submit-btn", style: "margin-top:4vh") do
							| Submit

app/views/home/index.html.slim
- if flash[:info]
    p class="alert alert-info"
        =link_to "#{flash[:info]}", edit_registration_path(current_user)
div class="jumbotron jumbotron-fluid" align="center"
    div.jumbotron-bg
        div.col-lg-12
          h1 class="text-light pt" Jumlah Campaign
          h3 class="text-light " = @total

br

div class="container"
  div class="row"
    div class="col-lg-12 text-center"
      h4.text-dark Campaign Terbaru
      br
    - @campaigns.each do |campaign|
     	div class="col-sm-4"
     	  = link_to campaign, :class => "custom-card" do
     	      div class="card h-100 mb-2 mt-2"
     	        = image_tag campaign.image_campaign.url, height: "200px", :class=>"card-img-top", :input_html => { :alt => "Campaign Image"}
     	        div class="card-body"
     	          h5 class="card-title text-dark"
     	            = campaign.campaign_title
     	        p class="card-text ml-4 text-muted"
     	          | Penggalang Dana : 
     	          = campaign.user.name
     	          span>
     	          = campaign.user.verified_user ? "(Verified) ": ""
                div class="progress" style="height:3px"
                  div class="progress-bar" style="width:#{ current_donation(campaign) }%"
     	        ul class="list-group list-group-flush"
     	          li class="list-group-item purple-text"
     	            | Target Donasi : 
     	            = number_to_currency campaign.donation_target
	div class="row"
    div class="col-lg-12 mt-5"
      div align="center"
		    = link_to "Lihat lebih banyak", campaigns_path, class: "purple-btn"

= render "layouts/footer"