config/routes.rb
Rails.application.routes.draw do
  resources :payments do
    collection do
      post :receive_webhook
    end
  end
  resources :campaign_complaints
  resources :doas
  resources :campaigns
  resources :products
  resources :suppliers
  resources :donations

  #User
  get 'users/profil/:name', to: 'users#index', as: 'users_index'
  get 'getting-started', to: 'users#getting_started', as: 'getting_started'

  #Devise
  devise_for :users, controllers: { omniauth_callbacks: 'users/omniauth_callbacks',
                                    registrations: 'users/registrations',
                                    confirmations: 'users/confirmations',
                                    sessions: 'users/sessions',
                                    passwords: 'users/passwords' }

  #Rails Admin
  mount RailsAdmin::Engine => '/admin', as: 'rails_admin'

  #CKEditor
  mount Ckeditor::Engine => '/ckeditor'

  #Root
  root to: "home#index"

  #Campaign
  post 'campaigns/approval/:id', to: 'campaigns#approval', as: 'approve_campaign'
  post 'campaigns/decline/:id', to: 'campaigns#decline', as: 'decline_campaign'
  post 'campaigns/save-donation/:id', to: 'campaigns#save_donation', as: 'save_donation'
  post 'campaigns/:id', to: 'campaigns#donate', as: 'campaign_donate'

  match "notification/handle" => "campaigns#receive_webhook", via: [:post]

  #Campaign Complaint
  get 'campaign_complaints/campaign/:id', to: "campaign_complaints#show_all", as: 'show_all_complaints'

  #Doa
  get '/doas/change-status/:id', to: "doas#change_status", as: 'change_status'

  #MONTHLY REPORT
  get 'monthly_product_report/:month', to: "report_products#monthly", as: 'month_product'
  get 'monthly_product_report_export/:month', to: "report_products#export", as: 'month_product_export'
  get 'monthly_donation_report/:month', to: "report_donation#monthly", as: 'month_donation'
  get 'monthly_donation_report_export/:month', to: "report_donation#export", as: 'month_donation_export'

  #NEWSLETTER
  get 'newsletters', to: 'newsletters#index'
  post 'newsletters/create', to: 'newsletters#create'

  #Cek Resi
  get 'cek_resi', to: 'home#cek_resi'

  #Donation
  get 'donation/cek', to: 'donations#cek', as: 'donation_cek'
  get 'campaigns/refund-donation/:order_id', to: 'campaigns#refund', as: 'refund_donation'

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/report_product.rb
class ReportProduct < ApplicationRecord
	def self.to_csv(options = {})
    CSV.generate(options) do |csv|
      csv << column_names

      all.each do |report|
        csv << report.attributes.values_at(*column_names)
      end
    end
  end
end

app/controllers/report_products_controller.rb
class ReportProductsController < ApplicationController

	def monthly
		@month = params[:month]
		@reports = ReportProduct.by_month(@month)
		@quantity = ReportProduct.by_month(@month).sum(:quantity)
		@price = ReportProduct.by_month(@month).sum(:price)
	end

	def export
		@month = params[:month]
		@reports = ReportProduct.by_month(@month)

		respond_to do |format|
			format.html { redirect_to month_product_path(@month) }
			format.csv { send_data @reports.to_csv, filename: "monthly-product-report-#{Date.today}.csv"}
			format.xls { send_data @reports.to_csv(col_sep: "\t"), filename: "monthly-product-report-#{Date.today}.xls" }
		end
	end
end

app/helpers/report_products_helper.rb
module ReportProductsHelper
end

app/views/report_products/export.html.erb
<?xml version="1.0"?>
<Workbook xmlns="urn:schemas-microsoft-com:office:spreadsheet"
  xmlns:o="urn:schemas-microsoft-com:office:office"
  xmlns:x="urn:schemas-microsoft-com:office:excel"
  xmlns:ss="urn:schemas-microsoft-com:office:spreadsheet"
  xmlns:html="http://www.w3.org/TR/REC-html40">
  <Worksheet ss:Name="Sheet1">
    <Table>
      <Row>
        <Cell><Data ss:Type="String">ID</Data></Cell>
        <Cell><Data ss:Type="String">Name</Data></Cell>
        <Cell><Data ss:Type="String">Quantity</Data></Cell>
        <Cell><Data ss:Type="String">Price</Data></Cell>
        <Cell><Data ss:Type="String">Created at</Data></Cell>
        <Cell><Data ss:Type="String">Updated at</Data></Cell>
      </Row>
    <% @report.each do |report| %>
      <Row>
        <Cell><Data ss:Type="Number"><%= report.id %></Data></Cell>
        <Cell><Data ss:Type="String"><%= report.name %></Data></Cell>
        <Cell><Data ss:Type="String"><%= report.quantity %></Data></Cell>
        <Cell><Data ss:Type="Number"><%= report.created_at %></Data></Cell>
        <Cell><Data ss:Type="Number"><%= report.updated_at %></Data></Cell>
      </Row>
    <% end %>
      <Row>
        <Cell><Data ss:Type="String">Total Quantity</Data></Cell>
        <Cell><Data ss:Type="Number"><%= @report.sum(:quantity) %></Data></Cell>
      </Row>
      <Row>
        <Cell><Data ss:Type="String">Total Price</Data></Cell>
        <Cell><Data ss:Type="Number"><%= @report.sum(:price) %></Data></Cell>
      </Row>
    </Table>
  </Worksheet>
</Workbook>

app/views/report_products/monthly.html.slim
div class="container mt-4 mb-4"
	h1 Monthly Report
	
	table class="table"
		thead
			tr
				th Name
				th Quantity
				th Price
				th Created at
				th Updated at
	
		tbody
			- @reports.each do |report|
				tr
					td = report.name
					td = report.quantity
					td = report.price
					td = report.created_at
					td = report.updated_at
	
		tfoot
			tr
				td colspan="4" align="right"
					b Total Quantity
				td 
					b = @quantity
			tr
				td colspan="4" align="right"
					b Total Price
				td
					b = @price
	br

	b = link_to 'Export (CSV)', month_product_export_path(month: Date.today.strftime("%B"), format: "csv")
	span>
	b = link_to 'Export (XLS)', month_product_export_path(month: Date.today.strftime("%B"), format: "xls")

	br
	
	table class="table"
		tr
			td 
				b = link_to 'January', month_product_path("January")
			td
				b = link_to 'February', month_product_path("February")
			td 
			 	b = link_to 'March', month_product_path("March")
			td
				b = link_to 'April', month_product_path("April")
			td
				b = link_to 'May', month_product_path("May")
			td
				b = link_to 'June', month_product_path("June")
			td
				b = link_to 'July', month_product_path("July")
			td
				b = link_to 'August', month_product_path("August")
			td
				b = link_to 'September', month_product_path("September")
			td
				b = link_to 'October', month_product_path("October")
			td
				b = link_to 'November', month_product_path("November")
			td
				b = link_to 'December', month_product_path("December")
	
	= link_to 'Back', products_path, :class => "btn btn-outline-secondary"