config/routes.rb
Rails.application.routes.draw do
  resources :payments do
    collection do
      post :receive_webhook
    end
  end
  resources :campaign_complaints
  resources :doas
  resources :campaigns
  resources :products
  resources :suppliers
  resources :donations

  #User
  get 'users/profil/:name', to: 'users#index', as: 'users_index'
  get 'getting-started', to: 'users#getting_started', as: 'getting_started'

  #Devise
  devise_for :users, controllers: { omniauth_callbacks: 'users/omniauth_callbacks',
                                    registrations: 'users/registrations',
                                    confirmations: 'users/confirmations',
                                    sessions: 'users/sessions',
                                    passwords: 'users/passwords' }

  #Rails Admin
  mount RailsAdmin::Engine => '/admin', as: 'rails_admin'

  #CKEditor
  mount Ckeditor::Engine => '/ckeditor'

  #Root
  root to: "home#index"

  #Campaign
  post 'campaigns/approval/:id', to: 'campaigns#approval', as: 'approve_campaign'
  post 'campaigns/decline/:id', to: 'campaigns#decline', as: 'decline_campaign'
  post 'campaigns/save-donation/:id', to: 'campaigns#save_donation', as: 'save_donation'
  post 'campaigns/:id', to: 'campaigns#donate', as: 'campaign_donate'

  match "notification/handle" => "campaigns#receive_webhook", via: [:post]

  #Campaign Complaint
  get 'campaign_complaints/campaign/:id', to: "campaign_complaints#show_all", as: 'show_all_complaints'

  #Doa
  get '/doas/change-status/:id', to: "doas#change_status", as: 'change_status'

  #MONTHLY REPORT
  get 'monthly_product_report/:month', to: "report_products#monthly", as: 'month_product'
  get 'monthly_product_report_export/:month', to: "report_products#export", as: 'month_product_export'
  get 'monthly_donation_report/:month', to: "report_donation#monthly", as: 'month_donation'
  get 'monthly_donation_report_export/:month', to: "report_donation#export", as: 'month_donation_export'

  #NEWSLETTER
  get 'newsletters', to: 'newsletters#index'
  post 'newsletters/create', to: 'newsletters#create'

  #Cek Resi
  get 'cek_resi', to: 'home#cek_resi'

  #Donation
  get 'donation/cek', to: 'donations#cek', as: 'donation_cek'
  get 'campaigns/refund-donation/:order_id', to: 'campaigns#refund', as: 'refund_donation'

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/product.rb
class Product < ApplicationRecord
	belongs_to :supplier

	RailsAdmin.config do |config|
      config.model 'Product' do

        export do
          field :id
          field :name
          field :price
          field :supplier
        end

        edit do
          field :name do
            required true
          end
          field :price do
            required true
          end
          field :supplier do
            required true
          end
        end
      end
    end
end

app/controllers/products_controller.rb
class ProductsController < ApplicationController
  before_action :set_product, only: [:show, :edit, :update, :destroy]

  # GET /products
  # GET /products.json
  def index
    @products = Product.order('name ASC').all
  end

  # GET /products/1
  # GET /products/1.json
  def show
  end

  # GET /products/new
  def new
    @product = Product.new
  end

  # GET /products/1/edit
  def edit
  end

  # POST /products
  # POST /products.json
  def create
    @product = Product.new(product_params)

    if Product.exists?(name: @product.name)

      pro = Product.find_by(name: @product.name)
      pro.update(quantity: pro.quantity+@product.quantity)
      @ReportProduct = ReportProduct.new(product_params)
      @ReportProduct.save

      respond_to do |format|
        format.html { redirect_to products_path, notice: 'Product was successfully updated.' }
      end

    else

      @product = Product.new(product_params)
      @ReportProduct = ReportProduct.new(product_params)
  
      respond_to do |format|
        if @product.save && @ReportProduct.save
          format.html { redirect_to @product, notice: 'Product was successfully created.' }
        else
          format.html { render :new }
        end
      end
    end
  end

  # PATCH/PUT /products/1
  # PATCH/PUT /products/1.json
  def update
    respond_to do |format|
      if @product.update(product_params)
        format.html { redirect_to @product, notice: 'Product was successfully updated.' }
      else
        format.html { render :edit }
      end
    end
  end

  # DELETE /products/1
  # DELETE /products/1.json
  def destroy
    @product.destroy
    respond_to do |format|
      format.html { redirect_to products_url, notice: 'Product was successfully destroyed.' }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_product
      @product = Product.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def product_params
      params.require(:product).permit(:name, :quantity, :price, :supplier_id)
    end
end

app/views/products/_form.html.slim
= simple_form_for(@product) do |f|
  = f.error_notification
  = f.error_notification message: f.object.errors[:base].to_sentence if f.object.errors[:base].present?

  .form-inputs
    = f.input :name
    = f.input :quantity, input_html: { min: 0 }
    = f.input :price
    = f.input :supplier_id, collection: Supplier.all, label: t('Suppliers'), value_method: :id

  .form-actions
    = f.button :submit, class: "btn-primary"

app/views/products/edit.html.slim
div class="container mt-4 mb-4"
	h1 Editing product
	
	== render 'form'
	
	=> link_to 'Show', @product
	'|
	=< link_to 'Back', products_path
	

app/views/products/index.html.slim
div class="container mt-4 mb-4"
  h1 List of Products
  
  table class="table"
    thead
      tr
        th scope="col" Name
        th scope="col" Quantity
        th scope="col" Price
        th scope="col" Supplier
        th scope="col"
        th scope="col"
        th scope="col"
  
    tbody
      - @products.each do |product|
        tr
          td = product.name
          td = product.quantity
          td = product.price
          td = product.supplier.name
          td = link_to 'Show', product
          td = link_to 'Edit', edit_product_path(product)
          td = link_to 'Destroy', product, data: { confirm: 'Are you sure?' }, method: :delete
  
  br
  
  => link_to 'New Product', new_product_path, :class => "btn btn-primary"
  span>
  =< link_to 'Report', month_product_path(Date.today.strftime("%B")), :class => "btn btn-outline-primary"
  
  br
  br
  
  = link_to 'Back', root_path, :class => "btn"

app/views/products/new.html.slim
div class="container mt-4 mb-4"
	h1 New product
	
	== render 'form'
	
	br
	
	= link_to 'Back', products_path, :class => "btn"
	

app/views/products/show.html.slim
div class="container mt-4 mb-4"
	p#notice = notice
	
	p
	  strong Name : 
	  = @product.name
	p
	  strong Quantity : 
	  = @product.quantity
	
	=> link_to 'Edit', edit_product_path(@product)
	'|
	=< link_to 'Back', products_path